      PROGRAM CMNBLK
      COMMON /MYDATA/I, J, K
      COMMON /OUTPUT/TOTAL, AVR
      INTEGER SUMALL, SUMALL2, TOTAL
      REAL AVR

      PRINT *, 'ENTER 3 INTEGERS'
      READ *, I, J, K
      PRINT *, 'SUM = ', SUMALL(I, J, K)
      PRINT *, 'AVERAGE = ', AVER(I, J, K)
      PRINT *, 'SUM2 = ', SUMALL2()
      PRINT *, 'AVERAGE2 = ', AVER2()

      CALL SUMAVG()
      PRINT *, 'THROUGH SUBROUTINE SUM = ', TOTAL, ' AVERAGE ', AVR
      END PROGRAM 

      INTEGER FUNCTION SUMALL(N1, N2, N3)
      SUMALL = N1 + N2 + N3
      END

      REAL FUNCTION AVER(N1, N2, N3)
      INTEGER SUMALL
      AVER = SUMALL(N1, N2, N3) / 3.0
      END

      INTEGER FUNCTION SUMALL2()
      COMMON /MYDATA/N1, N2, N3
      SUMALL2 = N1 + N2 + N3
      END

      REAL FUNCTION AVER2()
      COMMON /MYDATA/N1, N2, N3
      INTEGER SUMALL
      AVER2 = SUMALL(N1, N2, N3) / 3.0
      END      

      SUBROUTINE SUMAVG()
      COMMON /MYDATA/ VAL1, VAL2, VAL3
      COMMON /OUTPUT/ OUT1, OUT2

      INTEGER VAL1, VAL2, VAL3, OUT1
      REAL OUT2
      INTEGER SUMALL
      REAL AVER

      OUT1 = SUMALL(VAL1, VAL2, VAL3)
      OUT2 = AVER(VAL1, VAL2, VAL3)
      END