      PROGRAM CSVTST
      INTEGER PHY, CHEM, MATH, ROLLNO
      CHARACTER(30) STUNAM
      
    !   STUNAM = 'AMITABH BACHHAN'
    !   ROLLNO = 101
    !   PHY = 65
    !   CHEM = 72
    !   MATH = 84

    !   OPEN(UNIT=5, FILE='MARKS.CSV')
    !   WRITE(5,*)ROLLNO,',',STUNAM,',',PHY,',',CHEM,',',MATH
    !   CLOSE(5)

    !   OPEN(UNIT=6, FILE='MARKS.CSV')
    !   READ(6,*)ROLLNO,STUNAM,PHY,CHEM,MATH
    !   PRINT *, 'DATA FROM FILE = ', ROLLNO, STUNAM, PHY, CHEM, MATH
    !   CLOSE(6)


      
      OPEN(UNIT=55, FILE='MARKS.CSV', ERR=99)
10    READ (55,*,IOSTAT=IOS) ROLLNO,STUNAM,PHY,CHEM,MATH
      IF (IOS .NE. 0) THEN
        GOTO 99
      ENDIF
      WRITE(*,*)'DATA FROM FILE = ', ROLLNO, STUNAM, PHY, CHEM, MATH
C      PRINT *, 'DATA FROM FILE = ', ROLLNO, STUNAM, PHY, CHEM, MATH
      GOTO 10
99    CLOSE(55)
      END PROGRAM