      PROGRAM FILPROC

      CHARACTER(80) FILNAM
      CHARACTER(30) LINE

      PRINT *, 'ENTER FILE NAME'
      READ *, FILNAM

      OPEN(UNIT=10, FILE=FILNAM, STATUS='OLD')
      READ(10,FMT=100) LINE
100   FORMAT(A30)      
      PRINT *, LINE
      CLOSE(10)  
      
      END PROGRAM

    !   SUBROUTINE WRTFIL(FNAM, DA)